- name: Démo role
  hosts: all
  vars:
    mysql_users:
      - name: alice
        host: 127.0.0.1
        password: secret
        priv: '*.*:USAGE'

    # The default root user installed by mysql - almost always root
    mysql_root_home: /root
    mysql_root_username: root
    mysql_root_password: 1234

    # Set this to `true` to forcibly update the root password.
    mysql_root_password_update: true
    mysql_user_password_update: false

    mysql_databases:
      - name: produits
      - name: employes

  roles:
    - role: geerlingguy.mysql
      become: true