- name: Playbook TP4
  hosts: all
  become: true
  vars:
    server_port: 5555
  tasks:
    - name: Ensure SELinux is disabled
      ansible.posix.selinux:
        state: disabled
      when: ansible_os_family == 'RedHat'
      notify: Reboot and check SELinux

    - name: Ensure nginx is installed
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Ensure nginx is configured
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        validate: nginx -t -c %s
        owner: root
        group: root
        mode: '0644'
      notify: Restart nginx

  handlers:
    - name: Reboot and check SELinux
      ansible.builtin.reboot:
        test_command: 'egrep "^SELINUX=disabled" /etc/selinux/config'
      register: rebooted

    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
      when: rebooted is not defined
